/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CesiumMap: typeof import('./src/components/Cesium/CesiumMap.vue')['default']
    copy: typeof import('./src/components/Openlayers/OpenlayersMap copy.vue')['default']
    DataBox: typeof import('./src/components/Openlayers/dataBox.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    IconGisGlobe: typeof import('~icons/gis/globe')['default']
    IconGisLayerEdit: typeof import('~icons/gis/layer-edit')['default']
    IconGisLayerStack: typeof import('~icons/gis/layer-stack')['default']
    IconGisMeasure: typeof import('~icons/gis/measure')['default']
    IconGisMeasureArea: typeof import('~icons/gis/measure-area')['default']
    IconGisMeasureLine: typeof import('~icons/gis/measure-line')['default']
    IconGisPoiMap: typeof import('~icons/gis/poi-map')['default']
    IconGisPolygonPt: typeof import('~icons/gis/polygon-pt')['default']
    IconGisPolylinePt: typeof import('~icons/gis/polyline-pt')['default']
    IconGisZoomIn: typeof import('~icons/gis/zoom-in')['default']
    IconGisZoomOut: typeof import('~icons/gis/zoom-out')['default']
    IconIconParkClear: typeof import('~icons/icon-park/clear')['default']
    IconIconParkOutlineClearFormat: typeof import('~icons/icon-park-outline/clear-format')['default']
    IconTablerHandMove: typeof import('~icons/tabler/hand-move')['default']
    MyMap: typeof import('./src/components/MyMap/MyMap.vue')['default']
    OpenlayersMap: typeof import('./src/components/Openlayers/OpenlayersMap.vue')['default']
    PopDialoge: typeof import('./src/components/Openlayers/popDialoge.vue')['default']
    SgMap: typeof import('./src/components/Sg/SgMap.vue')['default']
    Station: typeof import('./src/components/Openlayers/station.vue')['default']
    StationList: typeof import('./src/components/Openlayers/stationList.vue')['default']
    StationSummary: typeof import('./src/components/Openlayers/stationSummary.vue')['default']
    Tool: typeof import('./src/components/Openlayers/Tool.vue')['default']
  }
}
